[versions]
kotlin = "2.3.0"
coroutines = "1.10.2"
aws = "1.5.110"
ktfmt = "0.25.0"
dokka = "2.1.0"
spring-boot = "4.0.1"
protobuf-plugin = "0.9.6"
protobuf-java = "4.33.2"
klogging = "7.0.13"
ktor = "3.3.3"
jreleaser = "1.21.0"


[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
aws-sqs-kotlin = { module = "aws.sdk.kotlin:sqs", version.ref = "aws" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf-java" }
klogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "klogging" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }

[plugins]
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
