[versions]
kotlin = "2.1.20"
coroutines = "1.10.2"
aws-sqs = "2.31.30"
ktfmt = "0.22.0"
dokka = "2.0.0"
spring-boot = "3.4.5"
protobuf-plugin = "0.9.5"
protobuf-java = "4.30.2"
klogging = "7.0.7"
ktor = "3.1.2"
jreleaser = "1.18.0"


[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
aws-sqs = { module = "software.amazon.awssdk:sqs", version.ref = "aws-sqs" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf-java" }
klogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "klogging" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }

[plugins]
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
